# -*- coding: utf-8 -*-
"""Employee Retention Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Is62JKg0OXUuZo5iwFrCggu_4AbOTZym
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("HR_comma_sep (2).csv")

# First few rows
df.head()

# Average values grouped by employee retention
df.groupby('left').mean(numeric_only=True)



pd.crosstab(df.salary, df.left).plot(kind='bar')

plt.xlabel("Salary")
plt.ylabel("Number of Employees")
plt.title("Salary vs Employee Retention")
plt.show()




pd.crosstab(df.Department, df.left).plot(kind='bar', figsize=(10,5))

plt.xlabel("Department")
plt.ylabel("Number of Employees")
plt.title("Department vs Employee Retention")
plt.show()


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

# Selecting important features
X = df[['satisfaction_level',
        'average_montly_hours',
        'promotion_last_5years',
        'salary']]

# Convert salary into numbers
le = LabelEncoder()
X = X.copy()
X['salary'] = le.fit_transform(X['salary'])

y = df['left']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

# Model
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)


from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy =", accuracy)

